project_id = "jpcdklqqhoewdnpgpjep"

[functions.flutterwave-payment]
verify_jwt = false

[functions.flutterwave-verify]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.explain-back-evaluate]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.spitch-tts]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.weekly-digest]
verify_jwt = false

[functions.send-payment-email]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.support-chatbot]
verify_jwt = false

[functions.referral]
verify_jwt = false

[functions.referral-notification]
verify_jwt = false

[functions.generate-lesson-audio]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false
